
general.import = [
# uncomment the flavour you want below:
#"~/.config/alacritty/tokyonight_night.toml"
# "~/.config/alacritty/tokyonight_moon.toml"
# "~/.config/alacritty/tokyonight_storm.toml"
# "~/.config/alacritty/tokyonight_day.toml"
"~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
opacity = 0.8
blur = true
decorations_theme_variant = "Dark"
dimensions = { columns = 110, lines = 36 }

[window.padding]
x = 10
y = 10

[font]
size = 10

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[terminal]
shell.program = "/bin/fish"

[cursor]
[cursor.style]
shape = "Underline"
blinking = "On"
